export const TESTING_WORKOUTS_DATA = [
  {
    id: 987654321,
    date: "Mon Mar 18 2024",
    name: "Monday | Upper Body",
    sets: 5,
    setRestTime: 180,
    blocks: 4,
    blockWorkTime: "40",
    blockRestTime: "15",
    exercises: ["Bench Press", "Pull-Ups", "Shoulder Press", "Bicep Curls"],
  },
  {
    id: 123456789,
    date: "Tue Mar 19 2024",
    name: "Tuesday | Core Blast",
    sets: 3,
    setRestTime: 240,
    blocks: 5,
    blockWorkTime: "30",
    blockRestTime: "25",
    exercises: [
      "Plank",
      "Russian Twists",
      "Leg Raises",
      "Mountain Climbers",
      "Bicycle Crunches",
    ],
  },
  {
    id: 135792468,
    date: "Wed Mar 20 2024",
    name: "Wednesday | Lower Body",
    sets: 4,
    setRestTime: 200,
    blocks: 3,
    blockWorkTime: "45",
    blockRestTime: "20",
    exercises: ["Squats", "Deadlifts", "Lunges"],
  },
  {
    id: 246813579,
    date: "Thu Mar 21 2024",
    name: "Thursday | Cardio Burn",
    sets: 6,
    setRestTime: 150,
    blocks: 4,
    blockWorkTime: "25",
    blockRestTime: "30",
    exercises: ["Jumping Jacks", "Burpees", "High Knees", "Box Jumps"],
  },
  {
    id: 369258147,
    date: "Fri Mar 22 2024",
    name: "Friday | Full Body",
    sets: 5,
    setRestTime: 180,
    blocks: 5,
    blockWorkTime: "35",
    blockRestTime: "15",
    exercises: [
      "Clean and Press",
      "Dumbbell Rows",
      "Leg Press",
      "Tricep Dips",
      "Calf Raises",
    ],
  },
  {
    id: 987654321,
    date: "Mon Mar 18 2024",
    name: "Monday | Yoga Flow",
    sets: 3,
    setRestTime: 240,
    blocks: 3,
    blockWorkTime: "50",
    blockRestTime: "30",
    exercises: ["Downward Dog", "Warrior II Pose", "Child's Pose"],
  },
  {
    id: 753951846,
    date: "Tue Mar 19 2024",
    name: "Tuesday | HIIT Madness",
    sets: 6,
    setRestTime: 120,
    blocks: 6,
    blockWorkTime: "30",
    blockRestTime: "20",
    exercises: [
      "Sprint Intervals",
      "Jump Squats",
      "Plank Jacks",
      "Push-Up Variations",
      "Mountain Climbers",
      "Bicycle Crunches",
    ],
  },
  {
    id: 159263748,
    date: "Wed Mar 20 2024",
    name: "Wednesday | Pilates Fusion",
    sets: 4,
    setRestTime: 180,
    blocks: 4,
    blockWorkTime: "40",
    blockRestTime: "20",
    exercises: ["Hundred", "Roll Up", "Single Leg Stretch", "Swimming"],
  },
  {
    id: 369852147,
    date: "Thu Mar 21 2024",
    name: "Thursday | Strength & Conditioning",
    sets: 5,
    setRestTime: 150,
    blocks: 5,
    blockWorkTime: "35",
    blockRestTime: "15",
    exercises: [
      "Kettlebell Swings",
      "Renegade Rows",
      "Jump Rope",
      "Box Jumps",
      "Sled Push",
    ],
  },
  {
    id: 258147369,
    date: "Fri Mar 22 2024",
    name: "Friday | Power Hour",
    sets: 6,
    setRestTime: 120,
    blocks: 6,
    blockWorkTime: "30",
    blockRestTime: "20",
    exercises: [
      "Power Cleans",
      "Snatch",
      "Push Press",
      "Barbell Rows",
      "Deadlifts",
      "Pull-Ups",
    ],
  },
];
